# Generated by Django 5.2.4 on 2025-08-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=20)),
                ('FEdu', models.CharField(max_length=20)),
                ('FImage', models.ImageField(upload_to='faculty_images/')),
            ],
        ),
    ]
