# Generated by Django 5.2.4 on 2025-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_No', models.IntegerField()),
                ('Emp_Name', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
    ]
